### ISSUE TITLE
Change wording from 'booted up' to avoid Bootstrap reference

### ISSUE THREAD

**Issue by karmatosed** [Automattic/components.underscores.me#1]

**Comment by laurelfulford** [comment]
Full sentence from original:

> If you’re just starting out, it’ll get you **booted up** without needing to reinvent the wheel or write a lot of custom code.

I listed some alternatives below; I found it hard to find a term as computery as 'booted up' without it also being confusing in this context :\ Let me know what works, and add your ideas!

> If you’re just starting out, it’ll get you up and running without needing to reinvent the wheel or write a lot of custom code.

> If you're just starting out, it'll get you powered up without needing to reinvent the wheel or write a lot of custom code.

> If you're just starting out, it'll get you configuring without needing to reinvent the wheel or write a lot of custom code.

> If you're just starting out, it'll get you building without needing to reinvent the wheel or write a lot of custom code.

> If you're just starting out, it'll get you processing without needing to reinvent the wheel or write a lot of custom code.

> If you're just starting out, it'll get you geared up without needing to reinvent the wheel or write a lot of custom code.

**Comment by sixhours** [comment]
I like "up and running", "building", and "geared up", leaning toward "building" because it's concrete/actionable, or "geared up" because of the gears in the design.

**Comment by sarahmonster** [comment]
I'm not convinced people would assume "booted = bootstrap", but "geared up" is probably the best of the provided option from a wordy-flow perspective. It also works with the "reinvent the wheel".

I wouldn't be opposed to rewriting this sentence altogether to make it a bit more active & less awkward—could be it's time for a round of considered copyedits. ;)

**Comment by kathrynwp** [comment]
Suggested tweak:

> Just starting out? Components will get you going quickly – no need to reinvent the wheel or write a lot of custom code.

"Geared up" doesn't say much to me and may also not be that well understood by non-native English speakers.

**Comment by alaczek** [comment]
Closing as we're re-writing the whole copy.
