### ISSUE TITLE
Theme type copy looks targeted at end user, not themer

### ISSUE THREAD

**Issue by ianstewart** [Automattic/components.underscores.me#104]
I just noticed this with the Business and Portfolio copy. Should it be tweaked so it's targeted at the themer making the theme? Not the end user? Both of those read like copy intended for a finished theme that a non-themer would use.

**Comment by kathrynwp** [comment]
Agreed. Suggested revisions:

**Business**
This starter theme gets right down to business with its front-page template featuring a custom header, prominent testimonials, and a custom content area. Testimonials can be displayed throughout the theme to lend extra credibility and instill customer confidence.

**Portfolio**
Shine a spotlight on creative work with this image-focused starter theme. A gridded layout keeps portfolio items separate from regular posts via a custom post type, while the blog template features a simple one-column look and a large featured-image header.

**Comment by ianstewart** [comment]
:100:

**Comment by kathrynwp** [comment]
Updated in https://github.com/Automattic/components.underscores.me/commit/8e06e6e5f3dffff6121f861930e0ae9e991fa876 in checkboxes-redesign branch, which will pushed to live site once other updates are merged in.
