### ISSUE TITLE
Provide live demo for each theme

### ISSUE THREAD

**Issue by philippebarbosa** [Automattic/components.underscores.me#105]
Hi,
Components look great but there is no preview for eachs themes on your website.
A live demo for each theme could be great !

Thanks a lot :)

**Comment by karmatosed** [comment]
@philippebarbosa thanks for the suggestion. We do want to explain the differences more. I'm keen to maybe not go the demo route as they aren't full themes, just starting points. Our goals are to create a browser at some point for the components, so this absolutely would come into that. For now, I'm going to close as think the browser we have planned covers this.

**Comment by karmatosed** [comment]
Adding in a new issue created to expose our plans: https://github.com/Automattic/theme-components/issues/196
