### ISSUE TITLE
Business has wrong template part slug

### ISSUE THREAD

**Issue by rdswd** [Automattic/components.underscores.me#108]
template-front.php in the page-templates folder in the business theme has incorrect slugs:
`get_template_part( 'components/content', 'hero' );`
`get_template_part( 'components/testimonials' ); `

Should be:

`get_template_part( 'components/content-hero/content', 'hero' );`
`php get_template_part( 'components/testimonials/testimonials' ); `

I imagine the issue is bigger than just the business theme.

**Comment by davidakennedy** [comment]
Hey @rdswd, thanks for the bug report! I filed this over on a different repo. This repository powers the Components site, and the generator that makes the themes, but isn't responsible for the theme code itself. See: https://github.com/Automattic/theme-components/issues/201
