### ISSUE TITLE
Missing featured-content content

### ISSUE THREAD

**Issue by CybMeta** [Automattic/components.underscores.me#112]
The magazine component is supposed to support featured-content from JetPack but the appropiate `add_theme_support()` is missing.

**Comment by laurelfulford** [comment]
Thank you for filing this issue, @CybMeta! I’ve moved it over to a different repo. This repository powers the Components site, and the generator that makes the themes, but isn't responsible for the theme code itself. 

The issue has been moved here: Automattic/theme-components#218

**Comment by CybMeta** [comment]
Ok. I didn't know about the differents repos.
Thank you.
