### ISSUE TITLE
Generator not moving some JavaScript files

### ISSUE THREAD

**Issue by davidakennedy** [Automattic/components.underscores.me#117]
What happened: When you generate the types, the base JS files aren’t being copied over, `navigation.js` and `skip-link-focus-fix.js`. So you get a 404 error on both.

Theme tested: Base (I don't see them in any theme type though)

What I expected: The files would be moved over during the generation process.

**Comment by davidakennedy** [comment]
One thing I realized while looking at this more closely:

The JavsScript for types is structured differently than other assets. See stylesheets for a type here:

https://github.com/Automattic/theme-components/tree/branchless-merge/types/blog-modern/assets

The JS files for that type are here:

https://github.com/Automattic/theme-components/tree/branchless-merge/assets/js

They're bundled with the other JS files that come with all types. Which is counterintuitive because any stylesheets a type adds are on their own. So my suggestion is to make the JS work the same, structure-wise. This would make this part of the generator easier to code.

Or maybe there's a reason that specific type JS file is bundled with the others, @karmatosed?

Thoughts as well, @mendezcode?

**Comment by karmatosed** [comment]
Blog modern had the sliding panel so the js came from there. Now we plan on that being a component, so it will pull in the component js.

**Comment by davidakennedy** [comment]
Okay, so for now, we'll move the that JS file into the type’s directory `/assets/js`. Components don't currently handle JS files, so we'll cross that bridge when we get there.

**Comment by mendezcode** [comment]
Fixed in f48997ae6d1893f61e0dbc23d4bd687d5de303f8

Cheers!

**Comment by davidakennedy** [comment]
Tested and fixed.
