### ISSUE TITLE
Highlighted text looks like link

### ISSUE THREAD

**Issue by karmatosed** [Automattic/components.underscores.me#122]
The following looks like a link when it's not. We should make sure if it looks like a link that it is, otherwise not include the styling:

<img width="501" alt="2016-06-02 at 15 06" src="https://cloud.githubusercontent.com/assets/253067/15747651/ac606766-28d3-11e6-98fc-2bac8cf308ea.png">

**Comment by alaczek** [comment]
I removed the highlight, it didn't make much sense to me anymore. I think we carried it over from the previous version and didn't re-examine.
