### ISSUE TITLE
Warning indication used for required field

### ISSUE THREAD

**Issue by karmatosed** [Automattic/components.underscores.me#125]
The triangle and color would indicate warning more than a required item. 

<img width="593" alt="2016-06-02 at 15 50" src="https://cloud.githubusercontent.com/assets/253067/15749327/de6d6618-28d9-11e6-9101-b6b9aab9d861.png">

**Comment by laurelfulford** [comment]
I forgot to mention this in my commit message (oops!), but I added some styles to the "formvalidate" branch to make the error message display with a more standard triangle.

Commit: https://github.com/Automattic/components.underscores.me/commit/45a46ec68b8215fd011b9d8109803300e8b961f0

Screenshots:

![image](https://cloud.githubusercontent.com/assets/177561/16212965/8b86141a-3700-11e6-8955-b24ca01b5fb7.png)

![image](https://cloud.githubusercontent.com/assets/177561/16212966/8fb3def0-3700-11e6-9764-c6d3541011eb.png)
