### ISSUE TITLE
Should buttons on mobile be hidden?

### ISSUE THREAD

**Issue by karmatosed** [Automattic/components.underscores.me#14]

**Comment by sixhours** [comment]
I think this makes sense. Maybe replace them with some kind of note to explain what device(s) one needs to build a theme with Components?

**Comment by karmatosed** [comment]
This would be an enhancement, but noting we still need to look at what we do for mobile.

**Comment by laurelfulford** [comment]
I think we should just leave it. It saves having to re-work parts of the site to include messages specific to mobile. It also technically works fine - people can generate a .zip from their phone, and if they decide to do that... ¯\_(ツ)_/¯

**Comment by karmatosed** [comment]
I really feel this is bad from an experience view to allow to download zips. There is potential for white screens as you download along with it just not being a brilliant experience. What we should do instead is at least ensure you can't download the zip file. At best we should show the types but not show the form. So you'd see them but not click to the form.

**Comment by laurelfulford** [comment]
The 'Choose a Type' and 'Configure' buttons are hidden for mobile devices in the above commit.
