### ISSUE TITLE
Generator: Undefined Offset Notice

### ISSUE THREAD

**Issue by davidakennedy** [Automattic/components.underscores.me#143]
On a fresh generation of theme types, a PHP notice is generated for each type:

```Notice: Undefined offset: 1 in /srv/www/wordpress-trunk/wp-content/themes/components.underscores.me/inc/components-generator.php on line 274```

That's here: https://github.com/Automattic/components.underscores.me/blob/master/inc/components-generator.php#L274

**Comment by mendezcode** [comment]
I'm not being able to replicate the notice. Mind sharing the replication steps? thanks!

**Comment by davidakennedy** [comment]
I tried to reproduce this again, and couldn't. I'll close it, and reopen if I see it again.
