### ISSUE TITLE
Generator: components_the_custom_logo() not defined in functions.php

### ISSUE THREAD

**Issue by nielslange** [Automattic/components.underscores.me#145]
All themes call the function THEME-NAME_the_custom_logo() within the header.php. That function should be defined within the functions.php, but it's not at the moment.

**Comment by alaczek** [comment]
Hi there!

Thank you for reporting! We have a PR ready for this issue, which should be merged soon: https://github.com/Automattic/theme-components/pull/282

**Comment by nielslange** [comment]
@alaczek: Thanks for letting me know!
