### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/components.underscores.me#15]
Add favicon to website

**Comment by sarahmonster** [comment]
Here's what I was thinking for this... saved as 512 png so it can be uploaded to wp-admin. 

<img width="198" alt="screen shot 2015-11-29 at 12 57 23" src="https://cloud.githubusercontent.com/assets/376315/11457135/eb815180-9698-11e5-817b-7687a9735dac.png">

![gear](https://cloud.githubusercontent.com/assets/376315/11457133/e435891e-9698-11e5-9ffe-3814f3532104.png)

Thoughts/feedback welcome!

**Comment by laurelfulford** [comment]
I like it! The symbol is a good fit with the rest of the design, and looks like it scales well :)

**Comment by sixhours** [comment]
Do it!

**Comment by sarahmonster** [comment]
Uploading once I can access the wp-admin for the site; it's making me crazy there isn't one there yet! :hankey:

**Comment by sarahmonster** [comment]
Done!
