### ISSUE TITLE
Animate pipe-output

### ISSUE THREAD

**Issue by sarahmonster** [Automattic/components.underscores.me#19]
This bit:

<img width="451" alt="screen shot 2015-11-21 at 16 32 13" src="https://cloud.githubusercontent.com/assets/376315/11319396/7251dda6-906d-11e5-9154-95ce71c3640d.png">

...could do with some super-subtle animation—maybe expanding up and then poofing out a little bit of smoke.

**Comment by alaczek** [comment]
Closing, since we're changing the layout of the pipes.
