### ISSUE TITLE
Move arrows to and from to right side

### ISSUE THREAD

**Issue by karmatosed** [Automattic/components.underscores.me#2]
The z pattern of use is in play on this site, which is awesome. You can use this more by putting the arrows for sliding to the right side.

**Comment by sixhours** [comment]
The more I look at it, the more I think this is a good idea. They'll feel more natural on the right.

**Comment by alaczek** [comment]
My only concern here is that it will make it even less obvious, that there's more then one type. I think this should be considered in conjunction with https://github.com/Automattic/components.underscores.me/issues/20 (Change copy or layout to indicate there are more types).

**Comment by davidakennedy** [comment]
We've moved away from slider. See #66.
