### ISSUE TITLE
Change copy or layout to indicate there are more types

### ISSUE THREAD

**Issue by karmatosed** [Automattic/components.underscores.me#20]
Currently it can be hard to know there are different types or that the slideshow works. A couple of ways this could be done are:

- Copy adjustments.
- A slight side bounce on load of the entire slide.

**Comment by ianstewart** [comment]
Perhaps (gasp) automatically sliding? Or a future iteration without a slider?

**Comment by sarahmonster** [comment]
Our original plan for this was to have the types all shown at once, but, after discussion, we decided that this might make the page too long, especially if there are more types added later down the line.

Lead-in text (#35) should help with this to some degree, as will #37.

**Comment by folletto** [comment]
> Our original plan for this was to have the types all shown at once, but, after discussion, we decided that this might make the page too long, especially if there are more types added later down the line.

Scroll *overwhelmingly* wins any sliding panel by a very very large measure.

Even not considering scroll: we get 89% on the default panel vs 2-3% on the others ([source](http://erikrunyon.com/2013/07/carousel-interaction-stats/)).

So: use carousels or sliding panels only for things you _don't_ want users to see. Scroll otherwise. ;)

**Comment by kathrynwp** [comment]
In addition to any panels/scroller, what about also adding some text so that people can more easily see what types are available, at a glance, without having to interact with the display at all? For example: "Check out the Modern Blog, Classic Blog, Business, Portfolio, and Magazine variations.

**Comment by ianstewart** [comment]
> Scroll overwhelmingly wins any sliding panel by a very very large measure.

A possible not-hard iteration might be to just have each section follow each other. Like, stacked one on top of the other so you can scroll past each one.

**Comment by davidakennedy** [comment]
We took care of this in #66. No slider, with a two-column grid and scrolling.
