### ISSUE TITLE
Animate pipe bulge on robot-puke

### ISSUE THREAD

**Issue by sarahmonster** [Automattic/components.underscores.me#29]
This thing should expand and bulge a bit whenever it pukes out a robot. 

<img width="563" alt="screen shot 2015-11-21 at 16 36 46" src="https://cloud.githubusercontent.com/assets/376315/11319423/4b4e0558-906e-11e5-9539-a024b50c232f.png">

**Comment by alaczek** [comment]
I'm wondering if this one is still valid, since we've moved away from the conveyor belt idea?

**Comment by davidakennedy** [comment]
Probably not. I vote close.

**Comment by sarahmonster** [comment]
It is not! I'm not sure the pipe will survive yet at all—but it probably won't continue in this format much longer.
