### ISSUE TITLE
Arrangement of elements in downloads panel gets weird at tablet-y breakpoints

### ISSUE THREAD

**Issue by sarahmonster** [Automattic/components.underscores.me#36]
Needs some fine-tuning:

<img width="830" alt="screen shot 2015-11-21 at 17 13 52" src="https://cloud.githubusercontent.com/assets/376315/11319569/60af3296-9073-11e5-8d47-39e44bc3fb7a.png">

**Comment by laurelfulford** [comment]
Note: this one's likely to be fixed with the changes we make for #66.

**Comment by davidakennedy** [comment]
#66 has been decided on and merged.
