### ISSUE TITLE
Sometimes robots get cut off when they land on the conveyor belt

### ISSUE THREAD

**Issue by sarahmonster** [Automattic/components.underscores.me#38]
It's a bit random, but in certain instances, the robots get their feet cut off when they land:

![awkward-bounce](https://cloud.githubusercontent.com/assets/376315/11319708/cfdbfefc-9077-11e5-917e-18b32c639b8f.gif)

**Comment by laurelfulford** [comment]
@sarahmonster: are you still seeing this issue? I haven't been able to recreate in the last couple days, and I'm wondering if I accidentally fixed it by swapping the PNG bots for SVGs. It's hard to tell if it's gone for real, or hiding :confused:

**Comment by sarahmonster** [comment]
I've been testing the last couple of days and it hasn't recurred. I'm thinking the SVG-swap might have done the trick! 

No idea why, but let's close this, and if it turns up again, I'll re-open.
