### ISSUE TITLE
Slideshow goes in the wrong direction

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/components.underscores.me#40]
When you click 'next', the slideshow moved to the right (rather than the left, with is more standard).

We actually deliberately set up the slideshow to go the 'wrong' way, to better match the expected behaviour of the conveyor belt. It might come off as weird, though, to folks who are more familiar with the 'typical' slideshow direction.

What do you all think?

**Comment by sixhours** [comment]
I think it makes more sense to follow the arrow's direction in this case. I click right, the slider scrolls to the right. It feels normal to me? I hadn't noticed the oddness until you mentioned it.

**Comment by davidakennedy** [comment]
No more slideshow, see #66, so closing this out.
