### ISSUE TITLE
Warning on theme activation

### ISSUE THREAD

**Issue by ianstewart** [Automattic/components.underscores.me#44]
Warning: call_user_func_array() [function.call-user-func-array]: First argument is expected to be a valid callback, 'component_s__site_logo_init' was given in /Users/ian/Sites/wpcore/wp-includes/plugin.php on line 525

**Comment by davidakennedy** [comment]
@ianstewart What theme type did you activate to get this?

I had previously fixed this elsewhere, but maybe it's happening in more than one spot.

**Comment by ianstewart** [comment]
@davidakennedy The Business type.

**Comment by laurelfulford** [comment]
Fixed here! https://github.com/Automattic/theme-pattern-library/pull/85
