### ISSUE TITLE
Confusing style.css header

### ISSUE THREAD

**Issue by ianstewart** [Automattic/components.underscores.me#45]
What I saw:

Theme Name: component_s
Theme URI: http://underscores.me/
Author: Underscores.me
Author URI: http://underscores.me/
Description: Description
Version: 1.0.0
License: GNU General Public License v2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html
Text Domain: component_s

Something like what I expected:

Theme Name: business_s
Theme URI: http://components.underscores.me/
Author: _s Components
Author URI: http://components.underscores.me/
Description: You’ve got a million things to worry about; don’t let your theme be another. This business starter theme comes with a front page template featuring a custom header, prominent testimonials, and a custom content area. Testimonials can be displayed throughout the theme to add authenticity to your business.
Version: 1.0
License: GNU General Public License v2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html
Text Domain: business_s

Note the updated description that also changes "A business starter …" to "This business starter …" and the simpler version.

**Comment by alaczek** [comment]
Related to #32

**Comment by davidakennedy** [comment]
Not really a bug, just something we didn't get to on first iteration. Closing because #32 will take care of it.
