### ISSUE TITLE
Default layouts in Built Themes

### ISSUE THREAD

**Issue by ianstewart** [Automattic/components.underscores.me#46]
Not sure if it's an issue with the Business theme in particular, or an error, but I was surprised to *not* have a default layout applied (with at least sidebar floating) when I activated the theme.

**Comment by sarahmonster** [comment]
It's an error! Should be fixed by https://github.com/Automattic/components.underscores.me/issues/46

**Comment by alaczek** [comment]
Business type fixed in https://github.com/Automattic/theme-components/pull/144
All other types were patched as well.
