### ISSUE TITLE
Refactor/simplify generator code after organizing Types into separate branches

### ISSUE THREAD

**Issue by danielwrobert** [Automattic/components.underscores.me#55]
See [open issue on Theme Pattern Library repo](https://github.com/Automattic/theme-pattern-library/issues/83) for details on recommendation to reorganize types into separate branches.

If we take this route, we will be able to simplify the generator code and also make it more flexible to be used by other tools, such as the CLI version.

Note from aforementioned Theme Pattern Library issue:
> As it stands, the zip generating functionality in components.underscores.me contains a good amount of hard-coded file paths. This was necessary because of the way the Theme Pattern Library is currently set up (which made perfect sense up until this point, I will add). Each Type is a build off of the Base Type and the differing files live in the Types folder broken up by each type. This means that, in order to generate a zip for each type, we needed to run through the Types directory, copy over/replace the needed folders and files for the requested type and then delete the Types folder in a cleanup process.

> All of this processing functionality would be unnecessary if we move out the different types into branches of their own. We would then be able to request a zip download from that particular branch, unzip it and find/replace the user-input project name strings throughout the project. The CLI generator has a similar complexity, based on the current structure, that could then be simplified.

**Comment by davidakennedy** [comment]
Addressed here:

https://github.com/Automattic/components.underscores.me/commit/7ddd3a597d75f1afd432a213aa3b106ffe1e62ac

And already merged into separate branches in library.
