### ISSUE TITLE
Replace 'mix-and-match' in intro text

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/components.underscores.me#56]
At the moment the introduction to the site reads:

> Instead of starting from scratch, mix and match from a collection of pre-made components to build your own custom starter theme.

V.1 of the site doesn't allow you to mix and match different patterns - instead, users can download different theme packages that already include what they'd need for a portfolio theme, business theme, etc. The text should reflect that for the short term, so it's not confusing to users.

**Comment by sarahmonster** [comment]
+1

Making a label for "copy". If we can tag any copyediting issues with this label, I'll start a larger PR later in the week to rework copy...

**Comment by alaczek** [comment]
Closing as we're re-writing the copy.
