### ISSUE TITLE
Generated zips include unnecessary files

### ISSUE THREAD

**Issue by sarahmonster** [Automattic/components.underscores.me#62]
I would recommend removing these files during the build process:

* everything in `docs`
* CONTRIBUTING.md
* README.md (ideally, we'd replace this with something more boilerplatey?)

It also looks as though blog traditional isn't deleting the `types` directory as expected/instructed by the code.

**Comment by karmatosed** [comment]
+1 to remove those files.

**Comment by davidakennedy** [comment]
Currently, `CONTRIBUTING.md` is not included in the builds. I can also exclude `README.md`. Do we even needs the `docs` directory? Maybe we just remove it? I would think we'd put that stuff in the wiki.

**Comment by karmatosed** [comment]
I'd say remove docs.

**Comment by davidakennedy** [comment]
Everything should be taken care of here.
