### ISSUE TITLE
Gravatar hovers show generic Gravatar & name 

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/components.underscores.me#74]
Moved from: https://github.com/Automattic/theme-pattern-library/issues/125

When you hover over any Gravatar in the contributor section, the display name is "gravatarmysteryman" and the image is the grey-and-white default Gravatar.

**Expected:** when you hover over a Gravatar, it should display the user's name/username, bio (if available), and a smaller version of their Gravatar.

![underscores components custom starter themes for faster wordpress theme development](https://cloud.githubusercontent.com/assets/7662449/12625414/af0d4b86-c501-11e5-9237-c6ac7872a418.png)

**Comment by laurelfulford** [comment]
The hovercards shouldn't be appearing at all - there are some different hover styles in the CSS that just display the user name.

I think this might need to be turned off in Jetpack (??)

https://jetpack.me/support/gravatar-hovercards/

**Comment by sarahmonster** [comment]
I'm generally not a fan of hovercards, and they're pretty disruptive here (also largely irrelevant, given that the action is to the user's Github, not their Gravatar profile). I'd vote for disabling them.

**Comment by sarahmonster** [comment]
Bye-bye, smelly hovercards!
