### ISSUE TITLE
Validate user input

### ISSUE THREAD

**Issue by sarahmonster** [Automattic/components.underscores.me#75]
Right now, the form doesn't handle user errors in a super elegant way. 

It looks like it's checking for a valid URL, but doesn't actually output an error message until you hit the "download" button:
![screen shot 2016-01-27 at 7 31 42 pm](https://cloud.githubusercontent.com/assets/376315/12625657/b03e14a6-c52c-11e5-831c-53097a7a663a.png)
...and it doesn't look super-pretty. 

It also seems super-happy to allow me to make a theme with the slug `eggs and w@ffl3s!` which it probably shouldn't do.

**Comment by davidakennedy** [comment]
Currently, we don't do any client-side validation, but we should. :smile: 

What you see there is what we get for free by using the `<input type="url">` in HTML5. It's Chrome's implementation of it, and each browser will be different.

There is some light server-side validation on some fields, but we need to do more. This is something I can attack in the future.

**Comment by karmatosed** [comment]
Future being after release or before? So long as we're secure we can refine.

**Comment by davidakennedy** [comment]
@karmatosed I was thinking after-release future. What we have now works and is a okay baseline. We can enhance later.

**Comment by BurlesonBrad** [comment]
Howdy folks!  Among all y'all rocket genius coders, I'm definitely in WAAAY over my head here :smile:  However, I've read a bazillion times to contribute when I can.  Does this help:

```
<input type="url" name="website" required pattern="https?://.+">

**Comment by jeffikus** [comment]
Taken a look and discussed with @davidakennedy , I don't see any blockers for a merge.
