### ISSUE TITLE
Just the basics, please - "Can't decide?" line out of place

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/components.underscores.me#76]
The phrase "Can’t decide?" in this blurb jumped out at me, because users may not yet have scrolled down to see that there are different types to chose from, so they may wonder "Can't decide what?" at this point on the page.

Should that line be removed entirely, or should the Base panel be moved below the Classic/Magazine/Business/Modern/Portfolio type?

![underscores components custom starter themes for faster wordpress theme development-1](https://cloud.githubusercontent.com/assets/7662449/12628491/78842a16-c511-11e5-991a-e24696a0da3f.png)

**Comment by sarahmonster** [comment]
Absolutely—the copy for this panel definitely needs to be reworked! I was thinking of tackling this later today or tomorrow, probably in tandem with a Long Hard Look at the first panel and how the design of these two areas fits together. Given that we've changed the structure of other elements, it's a good time to reconsider how this section works as well. :+1:

**Comment by karmatosed** [comment]
@sarahmonster are you able today or tmrw to look at this?
