### ISSUE TITLE
If the user doesn't enter an author, use a better fallback

### ISSUE THREAD

**Issue by sarahmonster** [Automattic/components.underscores.me#79]
When generating a theme without an author name, the automatically-generated author doesn't seem quite right:

`Author: Cold as Ice.Underscores.me`

![screen shot 2016-01-28 at 12 22 08 am](https://cloud.githubusercontent.com/assets/376315/12633120/45f97652-c555-11e5-9695-aa6e53c8a09b.png)

Looks like it's just substituting my theme name `Cold as Ice` for the `Components` line. Maybe it's best not to substitute here at all, or to nix the `.underscores.me` bit so it's less awkward?

**Comment by karmatosed** [comment]
After discussion, this probably happens in _s, we should fix for v2.

**Comment by davidakennedy** [comment]
We actually fixed this awhile back. In testing, I can't reproduce.
