### ISSUE TITLE
Review generated file structure

### ISSUE THREAD

**Issue by karmatosed** [Automattic/components.underscores.me#89]
Currently we output including all components folders. This is an issue for us to review this when we work on the new generation using config files.

**Comment by davidakennedy** [comment]
We've rethought the file structure in recent merges.

See: https://github.com/Automattic/components.underscores.me/commit/89ff36b8085c31cb5ff7df140d23e1fb0d8205c0

And: https://github.com/Automattic/theme-components/commit/b4959efe5b97f317a8422203bbb1d58d57b0b928

We can continue to iterate, but closing this out as complete.
