### ISSUE TITLE
Review generation and consider config files

### ISSUE THREAD

**Issue by karmatosed** [Automattic/components.underscores.me#90]
We have discussed about reviewing the way we generate and how we could use config files. This is the start of that.

**Comment by davidakennedy** [comment]
We're now using config files.

See: https://github.com/Automattic/components.underscores.me/commit/89ff36b8085c31cb5ff7df140d23e1fb0d8205c0

And: https://github.com/Automattic/theme-components/commit/b4959efe5b97f317a8422203bbb1d58d57b0b928

More documentation on this is coming soon.
