### ISSUE TITLE
Production site isn't pulling latest data from repo

### ISSUE THREAD

**Issue by sarahmonster** [Automattic/components.underscores.me#95]
Changes from #92 and #88 haven't been applied to the live site still. At first I thought it might be JS caching issue, but it looks more like the Github hooks are no longer working properly. 

I wonder if this is related to the plugin @mendezcode installed to edit the theme files via the wp-admin? That's the only thing I can think of that's changed in the interim.

**Comment by karmatosed** [comment]
This should be fixed now. It was an issue with a merge conflict caused potentially through file editing on the server. Now we have a block to prevent this. In the future lets make sure we all communicate all edits  and adjustments so we avoid tripping over each other.
